# This is a basic workflow to help you get started with Actions

name: paysages-azureens CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, paysages-azureens ]

    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      OWNER_EMAIL: ${{ secrets.OWNER_EMAIL }}
      GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Prepare env file
        run: |
          {
            echo "NODE_ENV=${NODE_ENV}"
            echo "FROM_EMAIL=${FROM_EMAIL}"
            echo "OWNER_EMAIL=${OWNER_EMAIL}"
            echo "GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}"
            echo "RESEND_API_KEY=${RESEND_API_KEY}"
          } >> .env
        
      # Add executable permission for using deploy script
      - name: Add executable permission
        run: chmod +x scripts/deploy.sh
          
      # Runs deploy script using the runners shell
      - name: Start deploy script
        run: ./scripts/deploy.sh
        
      # Clean unused images
      - name: Clean unused Docker images
        if: always()
        run: docker image prune -a -f
